project_id = "fgjypmlszuzkgvhuszxn"

[functions.admin-openai-keys]
verify_jwt = false

[functions.admin-openai-test]
verify_jwt = false

[functions.admin-openai-settings]
verify_jwt = false

[functions.admin-prompts]
verify_jwt = false