project_id = "fgjypmlszuzkgvhuszxn"

[functions.user-invitations]
verify_jwt = true

[functions.manage-user-roles]
verify_jwt = true

[functions.chat-legal]
verify_jwt = true

[functions.admin-openai-keys]
verify_jwt = false

[functions.admin-openai-test]
verify_jwt = false

[functions.admin-openai-settings]
verify_jwt = false

[functions.admin-prompts]
verify_jwt = false

[functions.database-cleanup]
verify_jwt = true

[functions.templates-xlsx]
verify_jwt = false

[functions.templates-csv]
verify_jwt = false

[functions.lgpd-requests]
verify_jwt = false

[functions.data-retention]
verify_jwt = true

[functions.automated-retention]
verify_jwt = false

[functions.mapa-testemunhas-processos]
verify_jwt = false

[functions.mapa-testemunhas-testemunhas]
verify_jwt = false

[functions.mapa-testemunhas-analysis]
verify_jwt = true

[functions.import-mapa-testemunhas]
verify_jwt = true

[functions.process-base-upload]
verify_jwt = true

[functions.beta-signup]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = true

[functions.create-version]
verify_jwt = true

[functions.publish-version]
verify_jwt = true

[functions.rollback-version]
verify_jwt = true

[functions.import-into-version]
verify_jwt = true
import_map = ""